### ISSUE TITLE
UI focus on Spanish -> English translations

### ISSUE THREAD

**Issue by ArtOfCode-** [CrowdRescueHQ/SCOT#77]
The broadcast input form doesn't validate anything, so you *can* enter only Spanish text and not English, but the UI doesn't reflect that.

 - [x] Remove the "required" and "optional" notes from the English and Spanish content fields; instead include a note that *at least one* of them is required.
 - [x] Include items that only have a Spanish version in the needs-translation list.
 - [ ] Make the translation list sortable by language.

**Comment by MeghanUX** [comment]
Yes, yes, yes! I can cry in joy, now!

**Comment by MeghanUX** [comment]
Does this "issue" also address how the UI will look for the Translators? Because it would be nice to be able to sort which kind of translation. Spanish -> English or English -> Spanish. Because these tasks often fall to two different sets of people. For example, with Google translate and a good dictionary, I can translate Spanish -> English. What's needed is "understanding" of Spanish original PLUS really good English skills. On the other hand, I wouldn't touch English -> Spanish. That way lies danger, danger.

**Comment by ArtOfCode-** [comment]
It certainly can do

**Comment by izwick-schachter** [comment]
The first 2 checkboxes will be resolved when #80 is merged. The third is an easy fix from there. Waiting on review from @ArtOfCode- on #80.

**Comment by izwick-schachter** [comment]
@ArtOfCode- @MeghanUX Any issues with me closing this and opening a new "sorting" issue?

**Comment by izwick-schachter** [comment]
See #91
