### ISSUE TITLE
Keep items in script long term

### ISSUE THREAD

**Issue by izwick-schachter** [CrowdRescueHQ/SCOT#84]
Broadcast would like a feature where items can stay in the script regardless of date settings. I think we should use `originated_at = NULL` and just always put those in the script.

**Comment by MeghanUX** [comment]
i think the issue here is that different items have different "expiry" dates and that SOME of them are known in advance. For example weather reports with things like flash flood warnings actually do have a (known at the time of issue) expiry date. Other things, like "bridge is out" need to stay in the broadcast until the bridge is fixed - which is unknown, but certainly longer than 3 days.

What makes it really frustrating to program is that, for some areas, we simply haven't found any "new" news, so that items "5 days old" are the "newest" thing we have. So perhaps something like this generate script with items 3 days old or newer, unless the ONLY items are older than 3 days, then include all items within a week of the last reported item.

**Comment by izwick-schachter** [comment]
From @MeghanUX: If you ALLOW future dates, then the broadcasters can keep setting dates in the future - for items they want to "stick around". I think that's brilliant!

**Comment by ArtOfCode-** [comment]
I think we do allow future

**Comment by izwick-schachter** [comment]
@ArtOfCode- status completed?

**Comment by ArtOfCode-** [comment]
Yup.
